/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ParticipanteRouteImport } from './routes/participante'
import { Route as PistaRouteImport } from './routes/pista'
import { Route as ReglasRouteImport } from './routes/reglas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipanteRoute = ParticipanteRouteImport.update({
  id: '/participante',
  path: '/participante',
  getParentRoute: () => rootRouteImport,
} as any)
const PistaRoute = PistaRouteImport.update({
  id: '/pista',
  path: '/pista',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglasRoute = ReglasRouteImport.update({
  id: '/reglas',
  path: '/reglas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/participante': typeof ParticipanteRoute
  '/pista': typeof PistaRoute
  '/reglas': typeof ReglasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/participante': typeof ParticipanteRoute
  '/pista': typeof PistaRoute
  '/reglas': typeof ReglasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/participante': typeof ParticipanteRoute
  '/pista': typeof PistaRoute
  '/reglas': typeof ReglasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/login' | '/participante' | '/pista' | '/reglas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/login' | '/participante' | '/pista' | '/reglas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/participante'
    | '/pista'
    | '/reglas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  ParticipanteRoute: typeof ParticipanteRoute
  PistaRoute: typeof PistaRoute
  ReglasRoute: typeof ReglasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participante': {
      id: '/participante'
      path: '/participante'
      fullPath: '/participante'
      preLoaderRoute: typeof ParticipanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pista': {
      id: '/pista'
      path: '/pista'
      fullPath: '/pista'
      preLoaderRoute: typeof PistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reglas': {
      id: '/reglas'
      path: '/reglas'
      fullPath: '/reglas'
      preLoaderRoute: typeof ReglasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  ParticipanteRoute: ParticipanteRoute,
  PistaRoute: PistaRoute,
  ReglasRoute: ReglasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
