/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CreditosRouteImport } from './routes/creditos'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ParticipanteRouteImport } from './routes/participante'
import { Route as PistaRouteImport } from './routes/pista'
import { Route as ReglasRouteImport } from './routes/reglas'
import { Route as LegalIndexRouteImport } from './routes/legal.index'
import { Route as LegalCreditosRouteImport } from './routes/legal.creditos'
import { Route as LegalPrivacidadRouteImport } from './routes/legal.privacidad'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditosRoute = CreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipanteRoute = ParticipanteRouteImport.update({
  id: '/participante',
  path: '/participante',
  getParentRoute: () => rootRouteImport,
} as any)
const PistaRoute = PistaRouteImport.update({
  id: '/pista',
  path: '/pista',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglasRoute = ReglasRouteImport.update({
  id: '/reglas',
  path: '/reglas',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCreditosRoute = LegalCreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacidadRoute = LegalPrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => LegalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/creditos': typeof CreditosRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/participante': typeof ParticipanteRoute
  '/pista': typeof PistaRoute
  '/reglas': typeof ReglasRoute
  '/legal/creditos': typeof LegalCreditosRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
  '/legal/': typeof LegalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/creditos': typeof CreditosRoute
  '/login': typeof LoginRoute
  '/participante': typeof ParticipanteRoute
  '/pista': typeof PistaRoute
  '/reglas': typeof ReglasRoute
  '/legal/creditos': typeof LegalCreditosRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
  '/legal': typeof LegalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/creditos': typeof CreditosRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/participante': typeof ParticipanteRoute
  '/pista': typeof PistaRoute
  '/reglas': typeof ReglasRoute
  '/legal/creditos': typeof LegalCreditosRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
  '/legal/': typeof LegalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/creditos'
    | '/legal'
    | '/login'
    | '/participante'
    | '/pista'
    | '/reglas'
    | '/legal/creditos'
    | '/legal/privacidad'
    | '/legal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/creditos'
    | '/login'
    | '/participante'
    | '/pista'
    | '/reglas'
    | '/legal/creditos'
    | '/legal/privacidad'
    | '/legal'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/creditos'
    | '/legal'
    | '/login'
    | '/participante'
    | '/pista'
    | '/reglas'
    | '/legal/creditos'
    | '/legal/privacidad'
    | '/legal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CreditosRoute: typeof CreditosRoute
  LegalRoute: typeof LegalRouteWithChildren
  LoginRoute: typeof LoginRoute
  ParticipanteRoute: typeof ParticipanteRoute
  PistaRoute: typeof PistaRoute
  ReglasRoute: typeof ReglasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creditos': {
      id: '/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof CreditosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participante': {
      id: '/participante'
      path: '/participante'
      fullPath: '/participante'
      preLoaderRoute: typeof ParticipanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pista': {
      id: '/pista'
      path: '/pista'
      fullPath: '/pista'
      preLoaderRoute: typeof PistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reglas': {
      id: '/reglas'
      path: '/reglas'
      fullPath: '/reglas'
      preLoaderRoute: typeof ReglasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/creditos': {
      id: '/legal/creditos'
      path: '/creditos'
      fullPath: '/legal/creditos'
      preLoaderRoute: typeof LegalCreditosRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacidad': {
      id: '/legal/privacidad'
      path: '/privacidad'
      fullPath: '/legal/privacidad'
      preLoaderRoute: typeof LegalPrivacidadRouteImport
      parentRoute: typeof LegalRoute
    }
  }
}

interface LegalRouteChildren {
  LegalCreditosRoute: typeof LegalCreditosRoute
  LegalPrivacidadRoute: typeof LegalPrivacidadRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalCreditosRoute: LegalCreditosRoute,
  LegalPrivacidadRoute: LegalPrivacidadRoute,
  LegalIndexRoute: LegalIndexRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CreditosRoute: CreditosRoute,
  LegalRoute: LegalRouteWithChildren,
  LoginRoute: LoginRoute,
  ParticipanteRoute: ParticipanteRoute,
  PistaRoute: PistaRoute,
  ReglasRoute: ReglasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
